version: '3.4'

services:
  nginx:
    image: nginx:1.21.6
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../../ssl/certificate.crt:/etc/nginx/certificate.crt
      - ../../ssl/www.mobileweb3.tech.key:/etc/nginx/www.mobileweb3.tech.key
      - ../../site/index.html:/etc/nginx/index.html
      - ../../site/style.css:/etc/nginx/style.css
      - ../../site/image:/etc/nginx/image
      - ../../site/vendor:/etc/nginx/vendor
    ports:
      - "80:80"
      - "443:443"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          memory: 1024M
          cpus: "1.0"
        reservations:
          memory: 512M
          cpus: "0.5"

  api:
    image: api
    ports:
      - "8090:8090"
    volumes:
      - ../../environment/api/.env:/app/.env
      - ../../environment/api/firebase-key.json:/app/firebase-key.json
    build:
      context: ..
      dockerfile: build/Dockerfile-api
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          memory: 1024M
          cpus: "2"
        reservations:
          memory: 512M
          cpus: "1"