version: '3.4'

services:
  nginx:
    image: nginx:1.21.6
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - $PROXY_CERT_PATH:/etc/nginx/certificate.crt
      - $PROXY_KEY_PATH:/etc/nginx/www.mobileweb3.tech.key
      - $PROXY_INDEX_PATH:/etc/nginx/index.html
      - $PROXY_STYLES_PATH:/etc/nginx/style.css
      - $PROXY_IMAGES_PATH:/etc/nginx/image
      - $PROXY_VENDOR_PATH:/etc/nginx/vendor
    ports:
      - "80:80"
      - "443:443"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          memory: 1024M
          cpus: "1.0"
        reservations:
          memory: 512M
          cpus: "0.5"

  api:
    image: api
    ports:
      - "8090:8090"
    volumes:
      - $API_ENV_PATH:/app/.env
    build:
      context: ..
      dockerfile: build/Dockerfile-api
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          memory: 1024M
          cpus: "2"
        reservations:
          memory: 512M
          cpus: "1"