basePath: /api
definitions:
  controller.apiResponse:
    properties:
      error:
        type: string
      isSuccess:
        type: boolean
      result: {}
    type: object
  controller.checkBalanceRequest:
    properties:
      walletAddress:
        type: string
    type: object
  service.BalanceResponse:
    properties:
      availableAmount:
        type: string
      stakedAmount:
        type: string
      totalAmount:
        type: string
    type: object
info:
  contact: {}
  description: API
  title: Swagger UI
  version: "1.0"
paths:
  /balance/check:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.checkBalanceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.apiResponse'
            - properties:
                result:
                  $ref: '#/definitions/service.BalanceResponse'
              type: object
      summary: Получить инфу о балансе
      tags:
      - balance
swagger: "2.0"
