basePath: /api
definitions:
  account.BalanceResponse:
    properties:
      availableAmount:
        type: string
      stakedAmount:
        type: string
      totalAmount:
        type: string
    type: object
  account.CreateAccountInput:
    properties:
      accountPath:
        type: integer
      chainPrefixes:
        items:
          type: string
        type: array
      coinType:
        type: integer
      indexPath:
        type: integer
      mnemonic:
        type: string
    type: object
  account.CreateMnemonicInput:
    properties:
      mnemonicSize:
        type: integer
    type: object
  account.KeyResponse:
    properties:
      addresses:
        items:
          type: string
        type: array
      key:
        type: string
    type: object
  account.RestoreAccountInput:
    properties:
      chainPrefixes:
        items:
          type: string
        type: array
      key:
        type: string
    type: object
  chain.PagedValidatorsResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/chain.Validator'
        type: array
      limit:
        type: integer
      offset:
        type: integer
    type: object
  chain.ShortResponse:
    properties:
      base:
        type: string
      bech32Prefix:
        type: string
      chainId:
        type: string
      chainName:
        type: string
      description:
        type: string
      display:
        type: string
      keyAlgos:
        items:
          type: string
        type: array
      logoPngUrl:
        type: string
      logoSvgUrl:
        type: string
      prettyName:
        type: string
      slip44:
        type: integer
      symbol:
        type: string
    type: object
  chain.Validator:
    properties:
      address:
        type: string
      commission:
        type: string
      description:
        type: string
      identity:
        type: string
      name:
        type: string
      tokens:
        type: string
      website:
        type: string
    type: object
  transaction.SendInput:
    properties:
      amount:
        type: string
      chainId:
        type: string
      from:
        type: string
      gasAdjusted:
        type: string
      gasPrice:
        type: string
      key:
        type: string
      memo:
        type: string
      to:
        type: string
    type: object
  transaction.SendInputFirebase:
    properties:
      amount:
        type: string
      chainId:
        type: string
      firebaseToken:
        type: string
      from:
        type: string
      gasAdjusted:
        type: string
      gasPrice:
        type: string
      key:
        type: string
      memo:
        type: string
      to:
        type: string
    type: object
  transaction.SendResponse:
    properties:
      txHash:
        type: string
    type: object
  transaction.SendResponseFirebase:
    properties:
      txHash:
        type: string
      withEvents:
        type: boolean
    type: object
  transaction.SimulateInput:
    properties:
      amount:
        type: string
      chainId:
        type: string
      from:
        type: string
      key:
        type: string
      memo:
        type: string
      to:
        type: string
    type: object
  transaction.SimulateResponse:
    properties:
      averageGasPrice:
        type: string
      gasAdjusted:
        type: string
      highGasPrice:
        type: string
      lowGasPrice:
        type: string
    type: object
  v1.apiResponse:
    properties:
      error:
        type: string
      isSuccess:
        type: boolean
      result: {}
    type: object
info:
  contact: {}
  description: API
  title: Swagger UI
  version: "1.0"
paths:
  /v1/accounts/balance:
    get:
      consumes:
      - application/json
      parameters:
      - description: id сети
        in: query
        name: chainId
        required: true
        type: string
      - description: адрес кошелька
        in: query
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/v1.apiResponse'
            - properties:
                result:
                  $ref: '#/definitions/account.BalanceResponse'
              type: object
      summary: Получить инфу о балансе
      tags:
      - accounts
  /v1/accounts/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/account.CreateAccountInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/v1.apiResponse'
            - properties:
                result:
                  $ref: '#/definitions/account.KeyResponse'
              type: object
      summary: Получение аккаунта по мнемонику
      tags:
      - accounts
  /v1/accounts/mnemonic:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/account.CreateMnemonicInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/v1.apiResponse'
            - properties:
                result:
                  type: string
              type: object
      summary: Создание мнемоника
      tags:
      - accounts
  /v1/accounts/restore:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/account.RestoreAccountInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/v1.apiResponse'
            - properties:
                result:
                  $ref: '#/definitions/account.KeyResponse'
              type: object
      summary: Получение аккаунта по ключу
      tags:
      - accounts
  /v1/chains:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/v1.apiResponse'
            - properties:
                result:
                  items:
                    $ref: '#/definitions/chain.ShortResponse'
                  type: array
              type: object
      summary: Получение данных о сетях
      tags:
      - chains
  /v1/chains/{id}/validators:
    get:
      consumes:
      - application/json
      parameters:
      - description: chainId
        in: path
        name: id
        required: true
        type: string
      - description: кол-во валидаторов для запроса
        in: query
        name: limit
        type: integer
      - description: кол-во валидаторов для пропуска
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/v1.apiResponse'
            - properties:
                result:
                  $ref: '#/definitions/chain.PagedValidatorsResponse'
              type: object
      summary: Получение данных о валидаторах
      tags:
      - chains
  /v1/transactions/send:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/transaction.SendInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/v1.apiResponse'
            - properties:
                result:
                  $ref: '#/definitions/transaction.SendResponse'
              type: object
      summary: Отправить транзакцию
      tags:
      - transactions
  /v1/transactions/send/firebase:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/transaction.SendInputFirebase'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/v1.apiResponse'
            - properties:
                result:
                  $ref: '#/definitions/transaction.SendResponseFirebase'
              type: object
      summary: Отправить транзакцию с подпиской на события тендерминта с пушами в
        firebase
      tags:
      - transactions
  /v1/transactions/simulate:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/transaction.SimulateInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/v1.apiResponse'
            - properties:
                result:
                  $ref: '#/definitions/transaction.SimulateResponse'
              type: object
      summary: Симуляция транзакции для расчета параметров
      tags:
      - transactions
swagger: "2.0"
