basePath: /api
definitions:
  account.BalanceInput:
    properties:
      address:
        type: string
      chainId:
        type: string
    type: object
  account.BalanceResponse:
    properties:
      availableAmount:
        type: string
      stakedAmount:
        type: string
      totalAmount:
        type: string
    type: object
  account.CreateAccountInput:
    properties:
      accountPath:
        type: integer
      chainPrefixes:
        items:
          type: string
        type: array
      coinType:
        type: integer
      indexPath:
        type: integer
      mnemonic:
        type: string
    type: object
  account.CreateMnemonicInput:
    properties:
      mnemonicSize:
        type: integer
    type: object
  account.KeyResponse:
    properties:
      addresses:
        items:
          type: string
        type: array
      key:
        type: string
    type: object
  account.RestoreAccountInput:
    properties:
      chainPrefixes:
        items:
          type: string
        type: array
      key:
        type: string
    type: object
  chain.ShortResponse:
    properties:
      base:
        type: string
      bech32Prefix:
        type: string
      chainId:
        type: string
      chainName:
        type: string
      description:
        type: string
      display:
        type: string
      keyAlgos:
        items:
          type: string
        type: array
      logoPngUrl:
        type: string
      logoSvgUrl:
        type: string
      prettyName:
        type: string
      slip44:
        type: integer
      symbol:
        type: string
    type: object
  http.apiResponse:
    properties:
      error:
        type: string
      isSuccess:
        type: boolean
      result: {}
    type: object
  transaction.SendInput:
    properties:
      amount:
        type: string
      chainId:
        type: string
      from:
        type: string
      gasAdjusted:
        type: string
      gasPrice:
        type: string
      key:
        type: string
      memo:
        type: string
      to:
        type: string
    type: object
  transaction.SendInputFirebase:
    properties:
      amount:
        type: string
      chainId:
        type: string
      firebaseToken:
        type: string
      from:
        type: string
      gasAdjusted:
        type: string
      gasPrice:
        type: string
      key:
        type: string
      memo:
        type: string
      to:
        type: string
    type: object
  transaction.SendResponse:
    properties:
      txHash:
        type: string
    type: object
  transaction.SendResponseFirebase:
    properties:
      txHash:
        type: string
      withEvents:
        type: boolean
    type: object
  transaction.SimulateInput:
    properties:
      amount:
        type: string
      chainId:
        type: string
      from:
        type: string
      key:
        type: string
      memo:
        type: string
      to:
        type: string
    type: object
  transaction.SimulateResponse:
    properties:
      averageGasPrice:
        type: string
      gasAdjusted:
        type: string
      highGasPrice:
        type: string
      lowGasPrice:
        type: string
    type: object
info:
  contact: {}
  description: API
  title: Swagger UI
  version: "1.0"
paths:
  /account/balance:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/account.BalanceInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/http.apiResponse'
            - properties:
                result:
                  $ref: '#/definitions/account.BalanceResponse'
              type: object
      summary: Получить инфу о балансе
      tags:
      - account
  /account/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/account.CreateAccountInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/http.apiResponse'
            - properties:
                result:
                  $ref: '#/definitions/account.KeyResponse'
              type: object
      summary: Получение аккаунта по мнемонику
      tags:
      - account
  /account/mnemonic:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/account.CreateMnemonicInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/http.apiResponse'
            - properties:
                result:
                  type: string
              type: object
      summary: Создание мнемоника
      tags:
      - account
  /account/restore:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/account.RestoreAccountInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/http.apiResponse'
            - properties:
                result:
                  $ref: '#/definitions/account.KeyResponse'
              type: object
      summary: Получение аккаунта по ключу
      tags:
      - account
  /chains/all:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/http.apiResponse'
            - properties:
                result:
                  items:
                    $ref: '#/definitions/chain.ShortResponse'
                  type: array
              type: object
      summary: Получение данных о сетях
      tags:
      - chain
  /transaction/send:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/transaction.SendInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/http.apiResponse'
            - properties:
                result:
                  $ref: '#/definitions/transaction.SendResponse'
              type: object
      summary: Отправить транзакцию
      tags:
      - transaction
  /transaction/send/firebase:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/transaction.SendInputFirebase'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/http.apiResponse'
            - properties:
                result:
                  $ref: '#/definitions/transaction.SendResponseFirebase'
              type: object
      summary: Отправить транзакцию с подпиской на события тендерминта с пушами в
        firebase
      tags:
      - transaction
  /transaction/simulate:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/transaction.SimulateInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/http.apiResponse'
            - properties:
                result:
                  $ref: '#/definitions/transaction.SimulateResponse'
              type: object
      summary: Симуляция транзакции для расчета параметров
      tags:
      - transaction
swagger: "2.0"
