basePath: /api
definitions:
  api.Response:
    properties:
      error:
        type: string
      isSuccess:
        type: boolean
      result: {}
    type: object
  balance.CheckResponse:
    properties:
      availableAmount:
        type: string
      stakedAmount:
        type: string
      totalAmount:
        type: string
    type: object
  balance.checkRequest:
    properties:
      walletAddress:
        type: string
    type: object
  chain.ShortResponse:
    properties:
      base:
        type: string
      bech32Prefix:
        type: string
      chainId:
        type: string
      chainName:
        type: string
      description:
        type: string
      display:
        type: string
      logoPngUrl:
        type: string
      logoSvgUrl:
        type: string
      prettyName:
        type: string
      slip44:
        type: integer
      symbol:
        type: string
    type: object
  transaction.SendInput:
    properties:
      amount:
        type: string
      from:
        type: string
      gasAdjusted:
        type: string
      gasPrice:
        type: string
      memo:
        type: string
      mnemonic:
        type: string
      to:
        type: string
    type: object
  transaction.SendResponse:
    properties:
      data:
        type: string
      gasUsed:
        type: integer
      gasWanted:
        type: integer
      height:
        type: integer
      rawLog:
        type: string
      txHash:
        type: string
    type: object
  transaction.SimulateInput:
    properties:
      amount:
        type: string
      from:
        type: string
      memo:
        type: string
      mnemonic:
        type: string
      to:
        type: string
    type: object
  transaction.SimulateResponse:
    properties:
      averageGasPrice:
        type: string
      gasAdjusted:
        type: string
      highGasPrice:
        type: string
      lowGasPrice:
        type: string
    type: object
info:
  contact: {}
  description: API
  title: Swagger UI
  version: "1.0"
paths:
  /balance/check:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/balance.checkRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.Response'
            - properties:
                result:
                  $ref: '#/definitions/balance.CheckResponse'
              type: object
      summary: Получить инфу о балансе
      tags:
      - balance
  /chains/all:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.Response'
            - properties:
                result:
                  items:
                    $ref: '#/definitions/chain.ShortResponse'
                  type: array
              type: object
      summary: Получение данных о сетях
      tags:
      - chain
  /transaction/send:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/transaction.SendInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.Response'
            - properties:
                result:
                  $ref: '#/definitions/transaction.SendResponse'
              type: object
      summary: Отправить транзакцию
      tags:
      - transaction
  /transaction/simulate:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/transaction.SimulateInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.Response'
            - properties:
                result:
                  $ref: '#/definitions/transaction.SimulateResponse'
              type: object
      summary: Симуляция транзакции для расчета параметров
      tags:
      - transaction
swagger: "2.0"
